# Generated by Django 3.1.4 on 2020-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('reviewer_name', models.CharField(max_length=40)),
                ('reviewer_email', models.CharField(max_length=40)),
                ('review_title', models.CharField(max_length=40)),
                ('review_location', models.CharField(max_length=40)),
                ('review_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('reviewer_name', models.CharField(max_length=40)),
                ('reviewer_email', models.CharField(max_length=40)),
                ('review_image', models.ImageField(upload_to='reviewImages')),
            ],
        ),
    ]
