# Generated by Django 3.1.4 on 2020-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_review_reviewimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='review_image',
            field=models.ImageField(upload_to='reviewimages'),
        ),
    ]
