# Generated by Django 3.1.4 on 2020-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20201216_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='review_image',
            field=models.ImageField(upload_to='static/reviewimages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(upload_to='static/profilephotos'),
        ),
    ]
